### ISSUE TITLE
Type-level compatibility with raw stdlib map and set

### ISSUE THREAD

**Issue by hcarty** [dbuenzli/asetmap#1]
Would you be interested in a patch to add this?  It seems like it should be possible, though I haven't tried to apply it to `asetmap` yet.

For example, given:

``` ocaml
module Map2(O : Map.OrderedType) : sig
  include Map.S
    with type 'a t = 'a Map.Make(O).t
    with type key = Map.Make(O).key
end = struct
  include Map.Make(O)
end
```

The follow types properly:

``` ocaml
module String_map1 = Map.Make(String)
module String_map2 = Map2(String)
let () = assert (String_map1.empty = String_map2.empty)
```

The main benefit being theoretical interoperability with other libraries using raw stdlib `Map`/`Set`

**Comment by hcarty** [comment]
The changes were very simple so I created a PR if you're interested.

**Comment by dbuenzli** [comment]
Thanks !
